(part "PTVS5V0S1UR_115"
    (packageRef "SOD123W")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Nexperia")
    (property "Manufacturer_Part_Number" "PTVS5V0S1UR,115")
    (property "Mouser_Part_Number" "771-PTVS5V0S1UR115")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nexperia/PTVS5V0S1UR115?qs=LMSg3oBIm%2FjAfyZn26r35g%3D%3D")
    (property "Arrow_Part_Number" "PTVS5V0S1UR,115")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ptvs5v0s1ur115/nexperia?utm_currency=USD&region=europe")
    (property "Description" "Nexperia PTVS5V0S1UR,115, Uni-Directional TVS Diode, 400W, 2-Pin SOD-123W")
    (property "Datasheet_Link" "https://assets.nexperia.com/documents/data-sheet/PTVSXS1UR_SER.pdf")
    (property "symbolName1" "PTVS5V0S1UR_115")
)
