(part "DMP2035UQ-7"
    (packageRef "SOT96P240X115-3N")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S") (portType INOUT))
        (port "3" (symbPinId 3) (portName "D") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "DMP2035UQ-7")
    (property "Mouser_Part_Number" "621-DMP2035UQ-7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/DMP2035UQ-7?qs=W%2FMpXkg%252BdQ5BI1lImHV7XA%3D%3D")
    (property "Arrow_Part_Number" "DMP2035UQ-7")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/dmp2035uq-7/diodes-incorporated.html?utm_currency=USD&region=europe")
    (property "Description" "MOSFETs MOSFET BVDSS: 8V-24V SOT23 T&R 3K")
    (property "Datasheet_Link" "https://www.diodes.com/assets/Datasheets/DMP2035U.pdf")
    (property "symbolName1" "DMP2035UQ-7")
)
